unframed/siteroupa/urls.py
from django.urls import include, path
from django.conf import settings
from . import views
from django.conf.urls.static import static
from django.contrib import admin

app_name = 'siteroupa'
urlpatterns = [
    path('', views.index, name='index'),
    path('account/', include('django.contrib.auth.urls')),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('store/page/<pk>', views.items_list, name='store'),
    path('store/item/<pk>', views.items_get, name='item'),
    path('store/create_item', views.item_create, name='create_item'),
    path('mulher/',views.mulher, name='mulher'),
    path('acessorios/' , views.acessorios, name='acessorios'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

unframed/unframed/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include

urlpatterns = [
    path('', include('siteroupa.urls')),
    path('admin/', admin.site.urls),
]

unframed/siteroupa/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


# Create your models here.
CATEGORY_CHOICES = (
    ('C', 'Clothes'),
    ('A', 'Accessories')
)

class CustomUser(AbstractUser):
    telephone = models.CharField(max_length=15, unique=True)
    address = models.CharField(max_length=150, blank=True)
    postal_code = models.CharField(max_length=10, blank=True)

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Subcategory(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default = 1)

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=120)
    price = models.FloatField(default=0)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, default = 1)
    description = models.CharField(max_length=250, default='', blank=True)
    color = models.CharField(max_length=30, blank=True)
    stock = models.IntegerField(default=0)
    onsale = models.BooleanField(default=False)
    pub_data = models.DateTimeField(default=timezone.now())
    main_image = models.ImageField(null=True, blank=True)
    #falta imagem

    def __str__(self):
        return self.name


class Order(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.FloatField(default = 0) #item * quantity
    address = models.CharField(max_length=100, default='', blank=True)
    phone = models.CharField(max_length=15, default='', blank=True)
    date = models.DateTimeField(default=timezone.now())
    status = models.BooleanField(default=False)

    def total_price(self):
        return self.item.price * self.quantity

class ItemImage(models.Model):
    item = models.ForeignKey('Item', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/siteroupa/images/')



unframed/siteroupa/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Item

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email',
                  'telephone', 'address', 'postal_code')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email',
                  'telephone', 'address', 'postal_code')


class ItemForm(forms.ModelForm):
    #images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)

    class Meta:
        model = Item
        fields = ['name', 'price', 'subcategory', 'description',
                  'color', 'stock', 'onsale', 'main_image']

unframed/siteroupa/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.views.generic.edit import CreateView
from .forms import CustomUserCreationForm, ItemForm
from .models import Item, Order, Category, Subcategory, ItemImage
from django.views import generic




def index(request):
    return render(request, 'siteroupa/index.html')

def login(request):
    return render(request, "siteroupa/login.html")

def mulher(request):
    return render(request, "siteroupa/mulher.html")

def acessorios(request):
    return render(request, "siteroupa/acessorios.html")

class SignupView(CreateView):
    form_class = CustomUserCreationForm
    success_url = '/account/login'
    template_name = 'registration/signup.html'

def items_list(request, pk=1):
    start = int(1*pk) - 1
    end = start + 15
    items = Item.objects.all()[start:end]
    context = {
        'items': items
    }
    return render(request, 'siteroupa/store.html', context)

def items_get(request, pk=1):
    items = Item.objects.get(pk=pk)
    context = {
        'item': items
    }
    return render(request, 'siteroupa/item.html', context)


def item_create(request):
    if request.method == 'POST':
        item_form = ItemForm(request.POST, request.FILES)
        if item_form.is_valid():
            item = item_form.save()  # Save the item

            # Handle uploaded images and create Image objects
            for image_file in request.FILES.getlist('images'):
                ItemImage.objects.create(item=item, image=image_file)

            return redirect('/store/page/1')  # Redirect to a success page
    else:
        item_form = ItemForm()

    return render(request, 'siteroupa/create_item.html', {'item_form': item_form})


unframed/siteroupa/templates/siteroupa/acessorios.html
<!DOCTYPE html>
{% extends 'siteroupa/main.html' %}

{% block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Acessórios</title>

</head>
<body>
<br>
<br>
  <h1>Disponível em breve</h1>
</body>
</html>

{% endblock %}

unframed/siteroupa/templates/siteroupa/create_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ item_form.as_p }}
    <label for="id_images">Upload Images:</label>
    <input type="file" name="images" id="id_images" multiple>
    <button type="submit">Create Item</button>
  </form>
</body>
</html>

unframed/siteroupa/templates/siteroupa/index.html
<!DOCTYPE html>
{% extends 'siteroupa/main.html' %}

{% block content %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unframed</title>

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- Adicionando jQuery -->
    <script>
        $(document).ready(function(){
            $(".elementos p").each(function(index) {
                if(index % 2 === 0) {
                    $(this).addClass("par");
                } else {
                    $(this).addClass("impar");
                }
            });
        });
    </script>
</head>

    <style>
        html, body {
             max-width: 100%;
             overflow-x: hidden;
        }

        body {
            background-color: #c79885;
            position: relative;
        }

        .image-container {
            display: flex; /* Use flexbox para alinhar as imagens lado a lado */
            justify-content: center;
            font-size: 0;
            margin-bottom: -100px;
        }
        .image-container a {
            flex: 1; /* Distribua o espaço igualmente entre as imagens */
            text-align: center;
        }
        .image-container img {
            width: 90%; /* Ajuste a largura das imagens (aumente conforme necessário) */
            height: 80%; /* Mantenha a proporção da imagem */
        }

        .titulo2 {
            color: white;
            font-family: "Bradley Hand";
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
            text-decoration: none;
            font-size: 25px;
            letter-spacing: 3px; /* Espaçamento entre as letras */
             }


        .button-container {
            text-align: center; /* Centraliza o conteúdo */
        }

.shop-now-button {
    font-family: "Arial", sans-serif;
    background-color: black;
    color: white;
    padding: 10px 23px;
    font-size: 20px;
    border: none;
    border-radius: 20px;
    text-decoration: none;
    cursor: pointer;
    transition: background-color 0.3s;
    display: inline-block; /* Torna o botão um elemento de bloco */
    max-width: 500px; /
    letter-spacing: 2px; /* Espaçamento entre as letras */

}

.button-container {
    text-align: center; /* Centraliza o conteúdo */
}

.shop-now-button {
            font-family:"Bradley Hand"
            }

    </style>

<body>
<br>
<br>
 <div class="logotipo">
    <a href="/">
        <img src="{% static 'siteroupa/images/logo.png' %}" class="rounded float-left" alt="LOGO" width="10%",
         height="10%" vspace="25" hspace="570">
    </a>
</div>
<div class="image-container">
    <a href="/">
        <img src="{% static 'siteroupa/images/inicial1.jpg' %}" class="rounded float-left" alt="LOGO" width="50%">
    </a>
    <a href="/">
        <img src="{% static 'siteroupa/images/videocerto.gif' %}" class="rounded float-left" alt="LOGO" width="50%">
    </a>
</div>
<a class="titulo2"> Unframed Artwork - Limited Series Artworks and Printed Garments - Enjoy being Unique </a>
<br>
<div class="button-container">
    <a class="nav-item nav-link shop-now-button" href="{% url 'siteroupa:store' 1 %}">Shop Now</a>
</div>
<br>
<br>
<footer class="bg-light text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Google -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright:
    <a class="text-white" href="https://Unframed.com/">Unframed.com</a>
  </div>
  <!-- Copyright -->
</footer>


</body>
{% endblock %}

unframed/siteroupa/templates/siteroupa/item.html
<!DOCTYPE html>
{% extends 'siteroupa/main.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>

    .imagem-pequena {
        width: 450px; /* Defina a largura desejada */
        height: 450px; /* Mantém a proporção da imagem */
        margin-left: 150px;
        display: block;
        float: left; /* Move the image to the left */
    }

    .name {
        color: black;
        font-style: italic;
        font-family: "Bradley Hand";
        font-size: 40px;
        float: right; /* Move the name to the right */
        margin-left: 50px;
    }

    .price {
        color: red;
        font-style: italic;
        float: right; /* Move the price to the right */
    }

</style>
<body>
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-md-4" style="display: flex;">
        <div class="object">
            <img src="{{ item.main_image.url }}" class="imagem-pequena" />
            <div style="display: flex; align-items: center;">
                <p class="name">{{ item.name }}</p>
                <p class="price" style="margin-left: 10px;">{{ item.price }}€</p>
            </div>
        </div>
    </div>
</div>

</body>
</html>
{% endblock %}

unframed/siteroupa/templates/siteroupa/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>siteroupa</title>
    <!-- Seus cabeçalhos e metadados aqui -->
</head>
<body>
    {% include 'siteroupa/navbar.html' %}

    <div class="conteudo">
        {% block content %}
        <!-- Seu conteúdo da página aqui -->
        {% endblock %}
    </div>


    <!-- Seus scripts e outras referências aqui -->
</body>
</html>

</html>

unframed/siteroupa/templates/siteroupa/mulher.html
<!DOCTYPE html>
{% extends 'siteroupa/main.html' %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mulher</title>
</head>
<body>
<br>
<br>
<h1>Roupa Mulher</h1>
</body>
</html>

{% endblock %}

unframed/siteroupa/templates/siteroupa/navbar.html
<!DOCTYPE html>

{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
{% load custom_tags %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="caminho-para-bootstrap/css/bootstrap.min.css">
<script src="caminho-para-bootstrap/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<style>
  .welcome {
            color: grey;
            font-family: "Optima", sans-serif;
            text-decoration: none;
            font-size: 20px;
           }
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'siteroupa:index' %}">Home <span class="sr-only"></span></a>
      <div class="dropdown">
        <a class="nav-link dropdown-toggle" type="button" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'siteroupa:store' 1 %}">T-shirts</a>
          <a class="dropdown-item" href="{% url 'siteroupa:mulher' %}">Accessories</a>
        </div>
      </div>
      {% if request.user.is_authenticated %}
      <a class="nav-item nav-link" href="{% url 'siteroupa:logout' %}">Logout</a>
      {% else %}
      <a class="nav-item nav-link" href="{% url 'siteroupa:login' %}">Login</a>
      {% endif %}
      <a class="nav-item nav-link" href="#">Carrinho</a>
    </div>
  </div>
  {% if request.user.is_authenticated %}
  <a class="welcome"> Welcome {{ request.user.username }} &nbsp;&nbsp; </a>
  {% endif %}
  <form2 class="form-inline mx-auto">
    <div class="input-group text-center">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-outline-success mr-1" type="submit">Search</button>
      </div>
    </div>
  </form2>
</nav>



unframed/siteroupa/templates/siteroupa/store.html
<!DOCTYPE html>
{% extends 'siteroupa/main.html' %}

{% block content %}
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>store</title>
</head>
<style>
    html, body {
             max-width: 100%;
             overflow-x: hidden;
        }
    .imagem-pequena {
            width: 350px; /* Defina a largura desejada */
            height: 350px; /* Mantém a proporção da imagem */
            margin: 0 auto;
            display: block;
            }


    .row {
            text-align: center; /* Centraliza o conteúdo */
           }

    .name {
        color: black;
        font-style: italic;
        font-family: "Bradley Hand";
        font-size: 20px;
    }

     .price {
        color: red;
        font-style: italic;
    }

</style>

<body>
<br>
<br>
<div class="logotipo">
    <a href="/">
        <img src="{% static 'siteroupa/images/logo.png' %}" class="rounded float-left" alt="LOGO" width="9%",
         height="10%" vspace="25" hspace="580">
    </a>
</div>
<div class="row">
    {% for item in items %}
        <div class="col-md-4 text-center">
            <div class="object text-center" href="">
             <!-- Adicionando a classe text-center -->
                <a href="{% url 'siteroupa:item' item.id %}"> <img src="{{ item.main_image.url }}" alt="clothes" class="imagem-pequena"/></a>
                <br>
                <div class="text-container">
                    <p class="name">{{ item.name }}</p>
                    <p class="price">{{ item.price }}€</p>
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}
</div>
<br>
<br>
<div class="row">
        {% endif %}
    {% endfor %}
</body>
</html>
{% endblock %}